# --- GraphSem no-gumbel specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200

lr: 0.0005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use the GraphSem_no_gumbel_Learner to train
standardise_returns: False
standardise_rewards: True


tamper: True
obs_tamper: [0.1, 0.01]


mac: "GraphSem_no_gumbel_mac"
agent: "GraphSem_no_gumbel"
agent_output_type: "q"
learner: "GraphSem_no_gumbel_learner"
double_q: True
mixer: "GraphSem_qmix"
use_rnn: True
hidden_dim: 128

# parameters of the graph coarsening
coarsening_embed_dim: 32
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# parameters of the transformer agent
enc_att_heads: 2
dec_att_heads: 4
att_enc_dim: 128
att_dec_dim: 32
num_layers: 2
dropout: 0

name: "GraphSem_no_gumbel"

t_max: 3005000 